#!/usr/bin/env node
/**
 * *****************************************************************************
 * 
 * The Entry Point for backend server
 *
 * 后端入口程序，用于管理和调度后台服务程序.
 *
 * *****************************************************************************
 */

// 设置进程名称
process.title = "org.zzlx.erpd";

// 加载主程序
import("./src/backend/main.mjs").then(m => {
  if (m && typeof m.default === "function") {
    const main = m.default;
    main(Array.prototype.slice.call(process.argv, 2)); // 执行主程序
  }
}).catch(err => {
  console.log("加载主程序时出错, 错误信息:", err);
});
