# 配置文件
type Profile {
  _id: ID!
  corporation: String
  uscc: String
  contact: String
  telephone: String
  domain: String
  icpc: String
  footer: String
}

input ProfileInput {
  corporation: String
  uscc: String
  contact: String
  telephone: String
  domain: String
  icpc: String
}
